///*
// * SyntaxHighlightingAssistant.java
// *
// * Created on 08 October 2006, 18:26
// */
//
//package com.uwyn.jhighlight.renderer;
//
//import java.io.IOException;
//
///**
// *
// * @author  matthew
// */
//public class SyntaxHighlightingAssistant extends javax.swing.JFrame {
//    private JavaXhtmlRenderer renderer = new JavaXhtmlRenderer();
//    /**
//     * Creates new form SyntaxHighlightingAssistant
//     */
//    public SyntaxHighlightingAssistant() {
//        initComponents();
//        
//        
//    }
//    
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
//    private void initComponents() {
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jScrollPane3 = new javax.swing.JScrollPane();
//        highlightedText = new javax.swing.JTextPane();
//        jLabel3 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        sourceCodeText = new javax.swing.JTextArea();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        htmlText = new javax.swing.JTextArea();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("Java Syntax Highlighting Assistant");
//        jLabel1.setText("HTML code:");
//
//        jLabel2.setText("Highlighted:");
//
//        highlightedText.setContentType("text/html");
//        highlightedText.setEditable(false);
//        jScrollPane3.setViewportView(highlightedText);
//
//        jLabel3.setText("Java source code:");
//
//        sourceCodeText.setColumns(20);
//        sourceCodeText.setFont(new java.awt.Font("Monospaced", 0, 12));
//        sourceCodeText.setLineWrap(true);
//        sourceCodeText.setRows(5);
//        sourceCodeText.setWrapStyleWord(true);
//        sourceCodeText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
//            public void propertyChange(java.beans.PropertyChangeEvent evt) {
//                sourceCodeTextPropertyChange(evt);
//            }
//        });
//        sourceCodeText.addKeyListener(new java.awt.event.KeyAdapter() {
//            @Override
//            public void keyReleased(java.awt.event.KeyEvent evt) {
//                sourceCodeTextKeyReleased(evt);
//            }
//            @Override
//            public void keyTyped(java.awt.event.KeyEvent evt) {
//                sourceCodeTextKeyTyped(evt);
//            }
//        });
//
//        jScrollPane1.setViewportView(sourceCodeText);
//
//        htmlText.setColumns(20);
//        htmlText.setEditable(false);
//        htmlText.setFont(new java.awt.Font("Monospaced", 0, 12));
//        htmlText.setLineWrap(true);
//        htmlText.setRows(5);
//        htmlText.setWrapStyleWord(true);
//        jScrollPane2.setViewportView(htmlText);
//
//        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
//                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
//                    .add(jLabel1)
//                    .add(jLabel2)
//                    .add(jLabel3)
//                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(jLabel3)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jLabel2)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jLabel1)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
//                .addContainerGap())
//        );
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void sourceCodeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sourceCodeTextKeyReleased
//        syncTextFields();
//    }//GEN-LAST:event_sourceCodeTextKeyReleased
//
//    private void sourceCodeTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sourceCodeTextPropertyChange
//        syncTextFields();
//    }//GEN-LAST:event_sourceCodeTextPropertyChange
//    
//    private void syncTextFields() {
//        String html; 
//        try {
//        html = "<!-- original source (easier to edit than the HTML highlighted version)\n" + sourceCodeText.getText() + "\n-->\n" + 
//                "<pre>\n" +  renderer.highlight("namea", sourceCodeText.getText(),
//                    "utf8", true) + "</pre>";
//        } catch (IOException ex) {
//            html = "parsing error";
//        }
//        
//        highlightedText.setText(html);
//        htmlText.setText(html);
//        
//    }
//    
//    private void sourceCodeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sourceCodeTextKeyTyped
//        //gsdfgsyncTextFields();
//        
//    }//GEN-LAST:event_sourceCodeTextKeyTyped
//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SyntaxHighlightingAssistant().setVisible(true);
//            }
//        });
//    }
//    
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JTextPane highlightedText;
//    private javax.swing.JTextArea htmlText;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JScrollPane jScrollPane3;
//    private javax.swing.JTextArea sourceCodeText;
//    // End of variables declaration//GEN-END:variables
//    
//}
