/*
 * DragAndDropQuestionEditor.java
 *
 * Created on 27 September 2006, 09:39
 */

package uk.co.bytemark.vm.enigma.inquisition.gui.screens.editor;

import javax.swing.JPanel;

/**
 * @author Matt
 */
public class AbstractDragAndDropQuestionEditorPanel extends JPanel {

    /** Creates new form DragAndDropQuestionEditor */
    public AbstractDragAndDropQuestionEditorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reuseFragmentsCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        extraFragmentsTable = new javax.swing.JTable();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        previewQuestionButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        previewExplanationButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        explanationTextArea = new javax.swing.JTextArea();

        reuseFragmentsCheckBox.setText( "Can fragments be reused?" );
        reuseFragmentsCheckBox.setBorder( javax.swing.BorderFactory.createEmptyBorder( 0, 0, 0, 0 ) );
        reuseFragmentsCheckBox.setMargin( new java.awt.Insets( 0, 0, 0, 0 ) );

        extraFragmentsTable.setModel( new javax.swing.table.DefaultTableModel( new Object[][] { { "extra fragment 1" }, { "extra fragment 2" }, { "extra fragment 3" } }, new String[] { "Extra fragments" } ) {
            Class<?>[] types = new Class[] { java.lang.String.class };

            @Override
            public Class<?> getColumnClass( int columnIndex ) {
                return types[columnIndex];
            }
        } );
        jScrollPane1.setViewportView( extraFragmentsTable );

        moveUpButton.setText( "Move up" );
        moveUpButton.setEnabled( false );

        moveDownButton.setText( "Move down" );
        moveDownButton.setEnabled( false );

        addButton.setText( "Add" );

        deleteButton.setText( "Delete" );
        deleteButton.setEnabled( false );

        jLabel1.setText( "Question text:" );

        previewQuestionButton.setText( "Preview..." );

        questionTextArea.setColumns( 20 );
        questionTextArea.setFont( new java.awt.Font( "Courier", 0, 12 ) );
        questionTextArea.setLineWrap( true );
        questionTextArea.setRows( 5 );
        questionTextArea.setText( "questionTextArea\n" );
        questionTextArea.setWrapStyleWord( true );
        jScrollPane3.setViewportView( questionTextArea );

        jLabel2.setText( "Explanation text:" );

        previewExplanationButton.setText( "Preview..." );

        explanationTextArea.setColumns( 20 );
        explanationTextArea.setFont( new java.awt.Font( "Courier", 0, 12 ) );
        explanationTextArea.setLineWrap( true );
        explanationTextArea.setRows( 5 );
        explanationTextArea.setText( "explanationTextArea\n" );
        explanationTextArea.setWrapStyleWord( true );
        jScrollPane2.setViewportView( explanationTextArea );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout( this );
        this.setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .add(
                    layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( layout.createSequentialGroup().add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( reuseFragmentsCheckBox ).add( jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE ) ).addPreferredGap( org.jdesktop.layout.LayoutStyle.UNRELATED ).add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.TRAILING ).add( moveUpButton ).add( addButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE ).add( deleteButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE ).add( moveDownButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE ) ) )
                        .add( layout.createSequentialGroup().add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.TRAILING ).add( jLabel1 ).add( jLabel2 ).add( previewExplanationButton ).add( previewQuestionButton ) ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE ).add( jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE ) ) ) ).addContainerGap() ) );

        layout.linkSize( new java.awt.Component[] { addButton, deleteButton, moveDownButton, moveUpButton }, org.jdesktop.layout.GroupLayout.HORIZONTAL );

        layout.setVerticalGroup( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add(
            org.jdesktop.layout.GroupLayout.TRAILING,
            layout.createSequentialGroup().addContainerGap().add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( layout.createSequentialGroup().add( jLabel1 ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( previewQuestionButton ) ).add( jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE ) ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( layout.createSequentialGroup().add( jLabel2 ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( previewExplanationButton ) ).add( jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE ) ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED )
                .add( layout.createParallelGroup( org.jdesktop.layout.GroupLayout.LEADING ).add( org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup().add( jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( reuseFragmentsCheckBox ) ).add( layout.createSequentialGroup().add( moveUpButton ).addPreferredGap( org.jdesktop.layout.LayoutStyle.RELATED ).add( moveDownButton ).add( 18, 18, 18 ).add( addButton ).add( 18, 18, 18 ).add( deleteButton ) ) ).addContainerGap() ) );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addButton;
    protected javax.swing.JButton deleteButton;
    protected javax.swing.JTextArea explanationTextArea;
    protected javax.swing.JTable extraFragmentsTable;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JScrollPane jScrollPane3;
    protected javax.swing.JButton moveDownButton;
    protected javax.swing.JButton moveUpButton;
    protected javax.swing.JButton previewExplanationButton;
    protected javax.swing.JButton previewQuestionButton;
    protected javax.swing.JTextArea questionTextArea;
    protected javax.swing.JCheckBox reuseFragmentsCheckBox;
    // End of variables declaration//GEN-END:variables

}
