/*
 * AbstractRenderAsHtmlDialog.java
 *
 * Created on 19 April 2008, 15:08
 */

package uk.co.bytemark.vm.enigma.inquisition.gui.screens;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 *
 * @author  matthew
 */
public class AbstractRenderAsHtmlDialog extends javax.swing.JDialog {
    
    /** Creates new form AbstractRenderAsHtmlDialog */
    public AbstractRenderAsHtmlDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        outputFileTextField = new javax.swing.JTextField();
        chooseOutputFileButton = new javax.swing.JButton();
        showAnswersCheckBox = new javax.swing.JCheckBox();
        addLinksCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make HTML Document From Questions");

        okButton.setText("OK");

        cancelButton.setText("Cancel");

        jLabel1.setText("Output file:");

        chooseOutputFileButton.setText("Choose...");

        showAnswersCheckBox.setSelected(true);
        showAnswersCheckBox.setText("Show answers");

        addLinksCheckBox.setSelected(true);
        addLinksCheckBox.setText("Add links between questions and answers");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(okButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(outputFileTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chooseOutputFileButton))
                    .add(showAnswersCheckBox)
                    .add(addLinksCheckBox))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelButton, chooseOutputFileButton, okButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(chooseOutputFileButton)
                    .add(outputFileTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showAnswersCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addLinksCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbstractRenderAsHtmlDialog dialog = new AbstractRenderAsHtmlDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    protected JButton getOkButton() {
        return okButton;
    }
    protected JButton getCancelButton() {
        return cancelButton;
    }
    
    protected JCheckBox getAddLinksCheckBox() {
        return addLinksCheckBox;
    }
    protected JCheckBox getShowAnswersCheckBox() {
        return showAnswersCheckBox;
    }
    protected JButton getChooseOutputFileButton() {
        return chooseOutputFileButton;
    }
    protected JTextField getOutputFileTextField() {
        return outputFileTextField;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addLinksCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton chooseOutputFileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JCheckBox showAnswersCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
